<?php

namespace Database\Seeders;

use App\Domain\Models\Setting;
use Illuminate\Database\Seeder;

class DefaultSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $defaults = [
            'company_name_ar' => 'مركز فحص المركبات',
            'company_name_en' => 'Vehicle Inspection Center',
            'company_address_ar' => '',
            'company_address_en' => '',
            'company_phone' => '',
            'company_email' => '',
            'company_website' => '',
            'company_tax_number' => '',
            'company_logo' => null,
            'company_favicon' => null,
            'pdf_notes_ar' => 'هذا التقرير صادر من نظام VIS لفحص المركبات.',
            'pdf_notes_en' => 'This report is generated by VIS - Vehicle Inspection System.',
            'score_excellent' => '90',
            'score_good' => '75',
            'score_needs_attention' => '50',
        ];

        foreach ($defaults as $key => $value) {
            Setting::firstOrCreate(['key' => $key], ['value' => $value]);
        }

        $this->command->info('Default settings created.');
    }
}